disabled = false
languageCode = "zh-tw"
languageName = "Chinese"
weight = 1
title = "結語JYu 的筆記"

[params]
displayName = "繁體中文"
isoCode = "zh"
rtl = false
dateFormat = "2 January 2006"

[params.author]
name = "結語JYu"
image = "img/author.png"
headline = "持續成長，追求平靜"
bio = "我是結語JYu"
links = [
  { x-twitter = "#" },
  { threads = "#" },
  { medium = "#" },
  { linkedin = "#" },
]