disabled = false
languageCode = "en"
languageName = "English"
weight = 2
title = "JYu's Notes"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

[params.author]
name = "結語JYu"
image = "img/author.png"
headline = "Keep growing, pursue peace."
bio = "Hi, I'm JYu"
links = [
  { x-twitter = "#" },
  { threads = "#" },
  { medium = "#" },
  { linkedin = "#" },
]