disabled = false
languageCode = "en"
languageName = "English"
weight = 0.9
title = "JYu's Notes"

[params]
displayName = "English"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = "img/author.png"

[params.author]
name = "結語JYu"
image = "img/author.png"
headline = "A generally awesome human"
bio = "A little bit about me"
links = [
  { twitter = "https://twitter.com/username" }
]