[[main]]
name = "文章列表"
pre = "list"
pageRef = "posts"
identifier = "CSm9U46jPy"
weight = 9_998

[[main]]
name = "標籤"
pre = "tag"
pageRef = "tags"
identifier = "IARIuWG0v1"
weight = 9_998

[[main]]
name = "分類"
pre = "substack"
pageRef = "categories"
identifier = "I52PdQ9sah"
weight = 9_997

[[footer]]
none = "none"