[[main]]
name = "文章列表"
pre = "list"
pageRef = "posts"
identifier = "CSm9U46jPy"
weight = 9_999

[[main]]
  name = "主題"
  pageRef = "topics"
  weight = 20

[[main]]
  pre = "github"
  name = "GitHub"
  url = "https://github.com/JYu1999"
  weight = 30

[[footer]]
  name = "Privacy"
  url = "#"
